import type { Metadata } from "next";
import { Inter, Rochester } from "next/font/google";

import Link from "next/link";

import "primereact/resources/themes/saga-green/theme.css";
import "primeicons/primeicons.css";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const rochester = Rochester({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layoutHeader">
          <Link href="/" className={`homeLink ${rochester.className}`}>
            Mon cahier de recette
          </Link>
          <Link href="/edit" className={`createLink `}>
            + Ajouter
          </Link>
        </div>
        {children}
        <div className="layoutFooter">
          <span className="copyright">©Thony974</span>
        </div>
      </body>
    </html>
  );
}
